include: package:lints/recommended.yaml

analyzer:
  exclude:
    - specs/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Enforce strict typing
    invalid_annotation_target: error
    invalid_assignment: error
    missing_required_param: error
    missing_return: error
    # Treat informational hints as errors for maximum type safety
    inference_failure_on_function_return_type: error
    inference_failure_on_untyped_parameter: error
    inference_failure_on_collection_literal: error

linter:
  rules:
    # Type safety
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_types_as_parameter_names: true

    # Strictness
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: true

    # Code quality
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
